// GENERATED by tool/export_spec_inputs.py — DO NOT EDIT.
// Re-run the tool after changing any prompt, safety JSON, the lexicon
// or pubspec.yaml; test/phase_a_version_pin_test.dart guards staleness.

const String kAppVersion = '1.0.0';
const String kBuildNumber = '3';
const String kLexiconVersion = 'v5-2026-09';
const String kPromptBundleHash = 'e45bf221b5a470242e2f11f151b7aae12086d336edc5bf1dff0608038610510d';
const String kGeneratedAt = '2026-09-16';

/// Per-artefact SHA-256 (path → hex) for the About page / audit.
const Map<String, String> kArtefactHashes = {
  'functions/prompts/siu_yan_v1.txt': '7f77797921ed36086abcd1740bd40d0edd6c205509cb9a027172316b5ec78290',
  'functions/prompts/ah_jan_ah_bak_v1.txt': '8efcae4cd46ba28f219bb0e49c6f533d5877950ffb21da5e29c8a73e148d6347',
  'functions/prompts/tung_tung_v1.txt': '251584dc7f1e503d63dc81e78b823e541342a75b9f7ed8b88d4457053bc08ecc',
  'docs/prompts/context_suffix_template.txt': 'a068c471634e6577a47eec379578334318d100df228ca1fed4e416c0702b2a22',
  'functions/prompts/safety_acknowledgements.json': '96fd03c84e3ece63216420de7e8ae60600daf2d798fde45865fe4075ab2db218',
  'functions/prompts/crisis_resources.json': '95c3e56aa879e960e089072afae5c6b83292b9d55a5346a71b085dd1d29f0c66',
  'assets/config/llm_fallback_messages.json': '2a495b99b4d715e5a745acaeb2a174c13b05d823a38d2ff18f911f63bc2e799c',
  'lib/core/safety/distress_detector.dart': '079af7a7741614501950f51f3c1537c3bc5e2bdccf9e6a59daf7001ead0b4cc7',
};
