// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMJdPkLLlvfZcG2NgSkwmRzXIYZkJ8_w',
    appId: '1:1036416880071:web:31f2fd4c41be99f1a91de2',
    messagingSenderId: '1036416880071',
    projectId: 'loneliness-pilot-dev',
    authDomain: 'loneliness-pilot-dev.firebaseapp.com',
    storageBucket: 'loneliness-pilot-dev.firebasestorage.app',
    measurementId: 'G-SFBYTGMH1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqcUpfq9VXrzR1Y-BcKK3ghTlki__U8nE',
    appId: '1:1036416880071:android:9cbe372316414dbba91de2',
    messagingSenderId: '1036416880071',
    projectId: 'loneliness-pilot-dev',
    storageBucket: 'loneliness-pilot-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7c_f9bjOFG2lzhGWT5VfO8YrQr5VUffA',
    appId: '1:1036416880071:ios:1e4db1760f64ac52a91de2',
    messagingSenderId: '1036416880071',
    projectId: 'loneliness-pilot-dev',
    storageBucket: 'loneliness-pilot-dev.firebasestorage.app',
    iosBundleId: 'hk.hku.hkuimse.withyouapp',
  );
}
