#!/usr/bin/env python3
"""Phase A baseline — export spec inputs + pin versions (Dev spec v1 2026-09 §V-1).

Run from the repo root:

    python3 tool/export_spec_inputs.py

Regenerates, deterministically from the source files:

  docs/safety/distress_detector_lexicon_<version>.md   (S-1 lexicon export)
  docs/prompts/agent_system_prompts_<date>.md          (three prompts + hashes)
  docs/prompts/context_suffix_template.txt             (persona_resolver output
                                                        format + V-2 injection)
  docs/release/phase_a_baseline_versions.md            (V-1 table for Manual §13)
  lib/core/version/build_info.g.dart                   (runtime-readable pin)

`promptBundleHash` recipe (mirrored in test/phase_a_version_pin_test.dart):
  sha256 over, in this fixed order, for each artefact:  "<relative path>\n"
  + raw file bytes + "\n".
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

DETECTOR = "lib/core/safety/distress_detector.dart"
RESOLVER = "lib/core/agents/persona_resolver.dart"
GATEWAY = "lib/core/llm/llm_gateway.dart"
PROMPTS = [
    "functions/prompts/siu_yan_v1.txt",
    "functions/prompts/ah_jan_ah_bak_v1.txt",
    "functions/prompts/tung_tung_v1.txt",
]
SUFFIX_TEMPLATE = "docs/prompts/context_suffix_template.txt"
ACKS = "functions/prompts/safety_acknowledgements.json"
CRISIS = "functions/prompts/crisis_resources.json"
FALLBACK = "assets/config/llm_fallback_messages.json"
SUMMARISER = "lib/core/agent_context/rolling_summary_compiler.dart"
FUNCTIONS_INDEX = "functions/index.js"

BUNDLE_ORDER = PROMPTS + [SUFFIX_TEMPLATE, ACKS, CRISIS, FALLBACK]


def read(path: str) -> str:
    with open(path, encoding="utf-8") as f:
        return f.read()


def sha256_file(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def git_commit(path: str | None = None) -> str:
    try:
        args = ["git", "log", "-1", "--format=%h"]
        if path:
            args += ["--", path]
        out = subprocess.check_output(args, text=True).strip()
        return out or "uncommitted"
    except Exception:  # noqa: BLE001
        return "unknown"


# ---------------------------------------------------------------------------
# 1. Lexicon export
# ---------------------------------------------------------------------------
GROUP_RE = re.compile(
    r"_TermGroup\(\s*(?:DistressLevel\.(\w+)|(hopelessnessTier))\s*,\s*DistressCategory\.(\w+)\s*,\s*(\[.*?\]|_hopelessnessTerms)\s*,?\s*\)",
    re.S,
)
TERM_RE = re.compile(r"'((?:[^'\\]|\\.)*)'|\"((?:[^\"\\]|\\.)*)\"")


def parse_lexicon(src: str):
    version = re.search(r"wordlistVersion = '([^']+)'", src).group(1)
    hopeless_tier = re.search(
        r"hopelessnessTier = DistressLevel\.(\w+);", src).group(1)
    hopeless_terms_block = re.search(
        r"_hopelessnessTerms = \[(.*?)\];", src, re.S).group(1)
    hopeless_terms = [a or b for a, b in TERM_RE.findall(hopeless_terms_block)]

    groups = []  # (tier, category, [terms])
    for m in GROUP_RE.finditer(src):
        tier = m.group(1) or hopeless_tier
        cat = m.group(3)
        body = m.group(4)
        if body == "_hopelessnessTerms":
            terms = list(hopeless_terms)
        else:
            body = re.sub(r"//[^\n]*", "", body)  # strip comments
            terms = [a or b for a, b in TERM_RE.findall(body)]
        groups.append((tier, cat, terms))
    return version, hopeless_tier, hopeless_terms, groups


TIER_ORDER = ["acute", "moderateInterrupt", "moderateReview", "low"]
TIER_CODE = {
    "acute": "acute",
    "moderateInterrupt": "moderate_interrupt",
    "moderateReview": "moderate_review",
    "low": "low",
}
CAT_CODE = {
    "ideation": "ideation", "worthlessness": "worthlessness",
    "selfHarm": "self_harm", "harmToOthers": "harm_to_others",
    "lossGrief": "loss_grief", "hardship": "hardship",
    "distress": "distress", "low": "low",
}


def write_lexicon_doc(version, hopeless_tier, hopeless_terms, groups, commit):
    per_tier = {t: [] for t in TIER_ORDER}
    for tier, cat, terms in groups:
        for t in terms:
            per_tier[tier].append((CAT_CODE[cat], t))
    # Listing order follows the Dart getter's check order: the S-7 group is
    # declared before _acuteGroups in source and lands at the head of its tier.
    lines = [
        f"# DistressDetector — Lexicon {version} (Phase A baseline)",
        "",
        "> Generated by `tool/export_spec_inputs.py` from "
        f"`{DETECTOR}` (commit `{commit}`). Do not edit by hand.",
        "",
        "| | |",
        "| --- | --- |",
        f"| Target source | `{DETECTOR}` |",
        f"| Wordlist version | `{version}` |",
        "| Base version | `v4-2026-07` (term set unchanged) |",
        f"| Generated | {_dt.date.today().isoformat()} |",
        "",
        "## Change v4 → v5 (S-1, S-7)",
        "",
        "* The 67 v4 `moderate` terms are split into **moderate_review** (19 —"
        " loss / grief + past hardship; LLM replies, nothing surfaced, logged"
        " for weekly review) and **moderate_interrupt** (48 — hopelessness,"
        " burden / worthlessness cognitions, nobody-cares, overwhelmed, bare"
        " 想死; LLM replies **plus** the per-agent template and the soft"
        " support sheet).",
        "* Check order is **acute → moderate_interrupt → moderate_review →"
        " low → none**, first hit wins. A message containing both 冇人理我"
        " (interrupt) and 過世 (review) routes to interrupt.",
        "* Every term now carries a `category` written to"
        " `turns.detector.category` (ideation / worthlessness / self_harm /"
        " harm_to_others / loss_grief / hardship / distress / low).",
        f"* **S-7** 絕望 family (`{'`, `'.join(hopeless_terms)}`) is a"
        f" configuration slot: currently `{TIER_CODE[hopeless_tier]}`"
        " (PI clinical sign-off pending). Flipping `hopelessnessTier` in"
        " the detector moves them with no other code change.",
        "* Acute terms, acute short-circuit and the 24 h notification path"
        " are unchanged from v4.",
        "",
        "## Matching",
        "",
        "Lower-cased substring `contains` over the whole message. No negation"
        " / sarcasm handling. Same detector in both arms.",
        "",
    ]
    for tier in TIER_ORDER:
        items = per_tier[tier]
        lines.append(f"## {TIER_CODE[tier]} ({len(items)} terms)")
        lines.append("")
        lines.append("| # | category | term |")
        lines.append("| --- | --- | --- |")
        for i, (cat, term) in enumerate(items, 1):
            lines.append(f"| {i} | {cat} | `{term}` |")
        lines.append("")
    out = f"docs/safety/distress_detector_lexicon_{version}.md"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    counts = {TIER_CODE[t]: len(per_tier[t]) for t in TIER_ORDER}
    return out, counts


# ---------------------------------------------------------------------------
# 2. Context suffix template (persona_resolver.dart output format + V-2 lines)
# ---------------------------------------------------------------------------
def write_suffix_template():
    src = read(RESOLVER)
    body = src[src.index("final lines = <String>[];"):src.index("final suffix =")]
    literals = []
    for m in re.finditer(r"lines\.add\(((?:[^;])*?)\);", body, re.S):
        expr = m.group(1)
        strs = [a or b for a, b in TERM_RE.findall(expr)]
        literals.append("".join(strs) if strs else "<computed>")
    gw = read(GATEWAY)
    inj = gw[gw.index("static String? injectThemeAndModule"):]
    inj = inj[:inj.index("\n  }\n")]
    inj_lits = [a or b for a, b in TERM_RE.findall(inj) if (a or b).startswith("[")]
    text = [
        "# Context suffix template — persona_resolver.dart output format",
        "# (Phase A baseline; generated by tool/export_spec_inputs.py — do not edit)",
        "#",
        "# The gateway appends this block after the persona prompt (server side,",
        "# after stripPII).  Lines in order; <computed> = value from agent_context.",
        "",
    ] + literals + [
        "",
        "# V-2 injection appended by LlmGateway.injectThemeAndModule (theme only",
        "# when the caller passes one; module always for agent calls):",
    ] + inj_lits
    os.makedirs(os.path.dirname(SUFFIX_TEMPLATE), exist_ok=True)
    with open(SUFFIX_TEMPLATE, "w", encoding="utf-8") as f:
        f.write("\n".join(text) + "\n")
    return SUFFIX_TEMPLATE


# ---------------------------------------------------------------------------
# 3. Prompts export
# ---------------------------------------------------------------------------
def prompt_version(path: str) -> str:
    first = read(path).splitlines()[0]
    m = re.search(r"v(\d+)\s*\(rev\s*([0-9-]+)\)", first)
    key = os.path.basename(path).replace(".txt", "")
    if not m:
        return key
    base = re.sub(r"_v\d+$", "", key)
    return f"{base}_v{m.group(1)}@{m.group(2)}"


def write_prompts_doc(date_tag: str, commit: str):
    out = f"docs/prompts/agent_system_prompts_{date_tag}.md"
    parts = [
        f"# Agent system prompts — Phase A baseline ({date_tag})",
        "",
        "> Generated by `tool/export_spec_inputs.py` from `functions/prompts/*.txt`"
        f" (commit `{commit}`). Do not edit by hand; edit the `.txt` and re-run.",
        "",
        "| file | promptVersion | SHA-256 |",
        "| --- | --- | --- |",
    ]
    for p in PROMPTS:
        parts.append(f"| `{p}` | `{prompt_version(p)}` | `{sha256_file(p)}` |")
    parts += [
        f"| `{SUFFIX_TEMPLATE}` | — | `{sha256_file(SUFFIX_TEMPLATE)}` |",
        "",
        "Temperatures (functions/index.js `_AGENT_TEMPERATURE`): siu_yan 0.7 ·"
        " ah_jan_ah_bak 0.5 · tung_tung 0.85; `max_tokens 800`, `top_p 0.95`.",
        "",
    ]
    for p in PROMPTS:
        parts += [f"---\n\n## `{p}`\n", "```text", read(p).rstrip("\n"), "```", ""]
    parts += [f"---\n\n## `{SUFFIX_TEMPLATE}`\n", "```text",
              read(SUFFIX_TEMPLATE).rstrip("\n"), "```", ""]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    return out


# ---------------------------------------------------------------------------
# 4. Bundle hash + version table + build_info.g.dart
# ---------------------------------------------------------------------------
def bundle_hash() -> str:
    h = hashlib.sha256()
    for p in BUNDLE_ORDER:
        h.update((p + "\n").encode("utf-8"))
        with open(p, "rb") as f:
            h.update(f.read())
        h.update(b"\n")
    return h.hexdigest()


def pubspec_version():
    m = re.search(r"^version:\s*([0-9.]+)\+(\d+)", read("pubspec.yaml"), re.M)
    return m.group(1), m.group(2)


def temperatures():
    src = read(FUNCTIONS_INDEX)
    block = src[src.index("_AGENT_TEMPERATURE = {"):src.index("};", src.index("_AGENT_TEMPERATURE = {"))]
    return dict(re.findall(r"(\w+):\s*([0-9.]+)", block))


def write_version_table(version, lexicon_ver, counts, bundle, commit):
    app_ver, build_no = version
    temps = temperatures()
    rows = [
        ("siu_yan_v1.txt", PROMPTS[0]),
        ("ah_jan_ah_bak_v1.txt (rev 2026-09)", PROMPTS[1]),
        ("tung_tung_v1.txt", PROMPTS[2]),
        ("context suffix 模板（persona_resolver.dart 输出格式 + V-2 注入）", SUFFIX_TEMPLATE),
        ("safety_acknowledgements.json", ACKS),
        ("crisis_resources.json（S-4，号码待 PI 核对）", CRISIS),
        (f"distress_detector.dart 词表（{lexicon_ver}）", DETECTOR),
        ("summariser prompt（rolling_summary_compiler.dart，LLM 生成）", SUMMARISER),
        ("fallback 文案 JSON", FALLBACK),
        ("functions/index.js（proxyDeepSeek：temperature / max_tokens / top_p / stripPII）", FUNCTIONS_INDEX),
    ]
    lines = [
        "# Phase A 基线版 — 版本钉死表（V-1，进 Manual §13）",
        "",
        "> 由 `tool/export_spec_inputs.py` 生成，日期 "
        f"{_dt.date.today().isoformat()}，仓库 HEAD `{commit}`。"
        " 参与者 1 入组前重新运行一次并把本表贴进 Manual。",
        "",
        f"* appVersion `{app_ver}` · buildNumber `{build_no}` · lexiconVersion `{lexicon_ver}`",
        f"* **promptBundleHash** `{bundle}`（前 8 位 `{bundle[:8]}`，关于页可核对）",
        f"* 词条数：acute {counts['acute']} · moderate_interrupt {counts['moderate_interrupt']}"
        f" · moderate_review {counts['moderate_review']} · low {counts['low']}",
        "",
        "| 工件 | 路径 | commit | SHA-256 |",
        "| --- | --- | --- | --- |",
    ]
    for label, path in rows:
        lines.append(f"| {label} | `{path}` | `{git_commit(path)}` | `{sha256_file(path)}` |")
    lines.append(
        f"| 三个 temperature | `{FUNCTIONS_INDEX}` | `{git_commit(FUNCTIONS_INDEX)}` |"
        f" siu_yan {temps.get('siu_yan')} / ah_jan_ah_bak {temps.get('ah_jan_ah_bak')}"
        f" / tung_tung {temps.get('tung_tung')} |")
    lines += [
        "",
        "promptBundleHash 计算方式：按固定顺序（三份 prompt → suffix 模板 → "
        "safety_acknowledgements.json → crisis_resources.json → "
        "llm_fallback_messages.json）对每个文件拼接 `路径\\n` + 原始字节 + `\\n` 后取 SHA-256。"
        " `test/phase_a_version_pin_test.dart` 用同一配方复算，生成值过期即测试失败。",
        "",
    ]
    out = "docs/release/phase_a_baseline_versions.md"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return out


def write_build_info(version, lexicon_ver, bundle):
    app_ver, build_no = version
    hashes = {p: sha256_file(p) for p in BUNDLE_ORDER + [DETECTOR]}
    body = [
        "// GENERATED by tool/export_spec_inputs.py — DO NOT EDIT.",
        "// Re-run the tool after changing any prompt, safety JSON, the lexicon",
        "// or pubspec.yaml; test/phase_a_version_pin_test.dart guards staleness.",
        "",
        f"const String kAppVersion = '{app_ver}';",
        f"const String kBuildNumber = '{build_no}';",
        f"const String kLexiconVersion = '{lexicon_ver}';",
        f"const String kPromptBundleHash = '{bundle}';",
        f"const String kGeneratedAt = '{_dt.date.today().isoformat()}';",
        "",
        "/// Per-artefact SHA-256 (path → hex) for the About page / audit.",
        "const Map<String, String> kArtefactHashes = {",
    ]
    for p, h in hashes.items():
        body.append(f"  '{p}': '{h}',")
    body += ["};", ""]
    with open("lib/core/version/build_info.g.dart", "w", encoding="utf-8") as f:
        f.write("\n".join(body))


def main() -> int:
    commit = git_commit()
    version = pubspec_version()
    lexicon_ver, hopeless_tier, hopeless_terms, groups = parse_lexicon(read(DETECTOR))
    lex_doc, counts = write_lexicon_doc(lexicon_ver, hopeless_tier, hopeless_terms, groups, commit)
    write_suffix_template()
    date_tag = lexicon_ver.split("-", 1)[1] if "-" in lexicon_ver else _dt.date.today().isoformat()[:7]
    prompts_doc = write_prompts_doc(date_tag, commit)
    bundle = bundle_hash()
    table = write_version_table(version, lexicon_ver, counts, bundle, commit)
    write_build_info(version, lexicon_ver, bundle)
    print(json.dumps({
        "lexicon": lex_doc, "counts": counts, "prompts": prompts_doc,
        "table": table, "promptBundleHash": bundle,
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
